"""remove user tokens

Revision ID: 0f7f7d752627
Revises: a97eb425b8af
Create Date: 2020-03-28 10:41:44.419116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f7f7d752627'
down_revision = 'a97eb425b8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('token', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=True)
    # ### end Alembic commands ###
