"""optimize store

Revision ID: 35875580996e
Revises: 71cc212e716f
Create Date: 2020-03-20 09:04:10.793498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35875580996e'
down_revision = '71cc212e716f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('sensor_value', sa.Text(), nullable=True))
    op.drop_column('sensor', 'sensorname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('sensorname', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('sensor', 'sensor_value')
    # ### end Alembic commands ###
