"""add user mqtt publish topic

Revision ID: 82b38b66edfd
Revises: ce25863c6c71
Create Date: 2020-03-24 21:36:41.582226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b38b66edfd'
down_revision = 'ce25863c6c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mqtt_publish_topic', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_mqtt_publish_topic'), 'user', ['mqtt_publish_topic'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mqtt_publish_topic'), table_name='user')
    op.drop_column('user', 'mqtt_publish_topic')
    # ### end Alembic commands ###
