"""remove fields in user model

Revision ID: b97fadc4eb66
Revises: 55bf51abb81b
Create Date: 2020-03-09 15:58:33.982477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b97fadc4eb66'
down_revision = '55bf51abb81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
