"""add mqtt_topic column in user table

Revision ID: fb25a48ab974
Revises: b5f4fb496e38
Create Date: 2020-03-08 11:27:30.181458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb25a48ab974'
down_revision = 'b5f4fb496e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mqtt_topic', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_mqtt_topic'), 'user', ['mqtt_topic'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mqtt_topic'), table_name='user')
    op.drop_column('user', 'mqtt_topic')
    # ### end Alembic commands ###
